# Generated by Django 4.2.2 on 2023-06-21 23:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ReneApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meme",
            name="image",
            field=models.ImageField(upload_to="media/"),
        ),
    ]
